install:
  - set PATH=%PATH%;C:\Qt\6.2.0\mingw81_64\bin;C:\Qt\Tools\mingw810_64\bin
  
build_script:
  - qmake TravianBlockchained.pro
  - mingw-make

artifacts:
  - path: release/TravianBlockchained.exe
