install:
  - set PATH=%PATH%;C:\Qt\6.2.0\mingw81_64\bin;C:\Qt\Tools\mingw810_64\bin
  - powershell "$file = 'TravianBlockchained.pro'; $content = Get-Content $file; $content[0..($content.length-20)]|Out-File $file -Encoding ascii"
  
build_script:
  - qmake TravianBlockchained.pro
  - mingw64-make

artifacts:
  - path: release/TravianBlockchained.exe
