install:
  - set PATH=%PATH%;C:\Qt\6.2.0\mingw81_32\bin;C:\Qt\Tools\mingw810_32\bin
  - powershell "$file = 'TravianBlockchained.pro'; $content = Get-Content $file; $content[0..($content.length-20)]|Out-File $file -Encoding ascii"
  
build_script:
  - dir C:\Qt\6.2.0\
  - qmake TravianBlockchained.pro
  - mingw32-make

artifacts:
  - path: release/TravianBlockchained.exe
