image:
- Ubuntu
- Visual Studio 2022

install:
  #- cmd: echo windows
  - sh: echo linux
  #- set PATH=%PATH%;C:\Qt\6.2.1\mingw81_64\bin;C:\Qt\Tools\mingw810_64\bin
  
build_script:
  - qmake TravianBlockchained.pro
  - cmd: mingw32-make
  - sh: make

artifacts:
  - path: release/TravianBlockchained.exe
